# Generated by Django 5.1.4 on 2025-01-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
